#include "TSCharacter2.h"
#include "TSGameState.h"
#include "Camera/CameraComponent.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "Kismet/GameplayStatics.h"
#include "TSPlayerController.h"
#include "Kismet/KismetMathLibrary.h"
#include "Components/SkeletalMeshComponent.h"

ATSCharacter2::ATSCharacter2()
{
	PrimaryActorTick.bCanEverTick = true;

	SpringArmComp = CreateDefaultSubobject<USpringArmComponent>(TEXT("SpringArm"));
	SpringArmComp->SetupAttachment(RootComponent);
	SpringArmComp->TargetArmLength = 300.0f;
	SpringArmComp->bUsePawnControlRotation = true;

	CameraComp = CreateDefaultSubobject<UCameraComponent>(TEXT("Camera"));
	CameraComp->SetupAttachment(SpringArmComp, USpringArmComponent::SocketName);
	CameraComp->bUsePawnControlRotation = false;

	NormalSpeed = 300.0f;
	SprintSpeed = 1000.0f;

	GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
	GetCharacterMovement()->bOrientRotationToMovement = false;
	bUseControllerRotationYaw = false;

	Tags.Add(TEXT("Player"));
}

// ë¬´ê¸° íƒ€ì…ìœ¼ë¡œ ë¬´ê¸° ì°¾ëŠ” í•¨ìˆ˜(ì´ì•Œ ì¶”ê°€ìš©)
AGunWeapon* ATSCharacter2::FindWeaponByType(FName WeaponType)
{
	for (AGunWeapon* Weapon : Weapons)
	{
		if (Weapon && Weapon->GetWeaponType() == WeaponType)
		{
			return Weapon;
		}
	}
	return nullptr;
}

void ATSCharacter2::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	if (UEnhancedInputComponent* EnhancedInput = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		if (ATSPlayerController* PlayerController = Cast<ATSPlayerController>(GetController()))
		{
			if (PlayerController->MoveAction)
			{
				EnhancedInput->BindAction(
					PlayerController->MoveAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::Move
				);
			}

			if (PlayerController->JumpAction)
			{
				EnhancedInput->BindAction(
					PlayerController->JumpAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::StartJump
				);
				EnhancedInput->BindAction(
					PlayerController->JumpAction,
					ETriggerEvent::Completed,
					this,
					&ATSCharacter2::StopJump
				);
			}


			if (PlayerController->LookAction)
			{
				EnhancedInput->BindAction(
					PlayerController->LookAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::Look
				);
			}


			if (PlayerController->SprintAction)
			{
				EnhancedInput->BindAction(
					PlayerController->SprintAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::StartSprint
				);
				EnhancedInput->BindAction(
					PlayerController->SprintAction,
					ETriggerEvent::Completed,
					this,
					&ATSCharacter2::StopSprint
				);
			}


			if (PlayerController->CrouchAction)
			{
				EnhancedInput->BindAction(
					PlayerController->CrouchAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::StartCrouch
				);

				EnhancedInput->BindAction(
					PlayerController->CrouchAction,
					ETriggerEvent::Completed,
					this,
					&ATSCharacter2::StopCrouch
				);
			}

			if (PlayerController->ReloadAction)
			{
				EnhancedInput->BindAction(
					PlayerController->ReloadAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::Reload
				);
			}

			if (PlayerController->FireAction)
			{
				EnhancedInput->BindAction(
					PlayerController->FireAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::Fire
				);
			}

			if (PlayerController->AimingAction)
			{
				EnhancedInput->BindAction(
					PlayerController->AimingAction,
					ETriggerEvent::Triggered,
					this,
					&ATSCharacter2::StartAiming
				);
				EnhancedInput->BindAction(
					PlayerController->AimingAction,
					ETriggerEvent::Completed,
					this,
					&ATSCharacter2::StopAiming
				);
			}
		}
	}
}

void ATSCharacter2::BeginPlay()
{
	Super::BeginPlay();

	// ê¸°ë³¸ì ìœ¼ë¡œ ì´ì„ ì•ˆì˜ëŠ” ìƒíƒœë¡œ ì‹œì‘í•˜ê²Œ falseë¡œ ì„¤ì •
	bFire = false;

	// ê¸°ë³¸ì ìœ¼ë¡œ ì¥ì „í•˜ëŠ” ì• ë‹ˆë©”ì´ì…˜ì´ ì•ˆë‚˜ì˜¤ë„ë¡ falseë¡œ ì„¤ì •
	bIsReloading = false;

	DefaultFOV = CameraComp->FieldOfView;
	DefaultCameraOffset = SpringArmComp->SocketOffset; // ì¹´ë©”ë¼ ì»´í¬ë„ŒíŠ¸ ê¸°ë³¸ ìœ„ì¹˜ë¥¼ ì €ì¥í•œë‹¤.

	MaxShotGunBullet = 2;
	CurrentShotGunBullet = MaxShotGunBullet;

	
	if (CurrentShotGunBullet <= 0)
	{
		CurrentShotGunBullet = 0;
	}
	else if (CurrentShotGunBullet >= 2)
	{
		CurrentShotGunBullet = 2;
	}

	ATSGameState* GameState = Cast<ATSGameState>(UGameplayStatics::GetGameState(GetWorld()));
	if (GameState)
	{
		GameState->SetShotGunBulletCount(CurrentShotGunBullet); //GameStateë¡œ ë°ì´í„° ì „ì†¡
	}

	//í…ŒìŠ¤íŠ¸
	if (!WeaponChildActor)
	{
		WeaponChildActor = FindComponentByClass<UChildActorComponent>();
	}

	if (!WeaponChildActor)
	{
		UE_LOG(LogTemp, Error, TEXT("WeaponChildActorê°€ nullptrì…ë‹ˆë‹¤! ë¸”ë£¨í”„ë¦°íŠ¸ì—ì„œ ì„¤ì •ë˜ì—ˆëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."));
		return;
	}

	AActor* ChildActor = WeaponChildActor->GetChildActor();
	if (!ChildActor)
	{
		UE_LOG(LogTemp, Error, TEXT("WeaponChildActor->GetChildActor()ê°€ nullptrì…ë‹ˆë‹¤! ë¸”ë£¨í”„ë¦°íŠ¸ì—ì„œ ì„¤ì •ë˜ì—ˆëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."));
		return;
	}

	AGunWeapon* EquippedWeapon = Cast<AGunWeapon>(ChildActor);
	if (EquippedWeapon)
	{
		UE_LOG(LogTemp, Warning, TEXT("ChildActorì—ì„œ ë¬´ê¸° ì¥ì°© ì„±ê³µ: %s"), *EquippedWeapon->GetName());
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("ChildActorë¥¼ AGunWeaponìœ¼ë¡œ ìºìŠ¤íŒ… ì‹¤íŒ¨! BP_ShotGun ë˜ëŠ” BP_M16ì´ AGunWeaponì„ ìƒì†ë°›ì•˜ëŠ”ì§€ í™•ì¸í•˜ì„¸ìš”."));
	}
}

void ATSCharacter2::Tick(float DeltaTime)
{

	Super::Tick(DeltaTime);

	FaceMouseDirection();

	if (GetCharacterMovement()->MaxWalkSpeed == SprintSpeed)
	{
		if (LastMoveInput.X <= 0.0f || !FMath::IsNearlyZero(LastMoveInput.Y))
		{
			StopSprint(FInputActionValue());
		}
	}

	if (!IsFiring && LastMoveInput.IsNearlyZero() && !LastMoveDirection.IsNearlyZero())
	{
		AddMovementInput(LastMoveDirection, 1.0f);
	}

	// ì´ë™ ì‚¬ìš´ë“œ ì¬ìƒ
	PlayFootstepSound();
}

void ATSCharacter2::Move(const FInputActionValue& value)
{
	if (!Controller || bIsReloading) return; // ì¬ì¥ì „ ì¤‘ì´ë©´ ì´ë™ ë¶ˆê°€

	FVector2D MoveInput = value.Get<FVector2D>();
	if (FMath::IsNearlyZero(MoveInput.X) && FMath::IsNearlyZero(MoveInput.Y))
	{
		return;
	}

	LastMoveInput = MoveInput;

	FRotator ControlRotation = Controller->GetControlRotation();
	FRotator YawRotation(0, ControlRotation.Yaw, 0);

	FVector Forward = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::X);
	FVector Right = FRotationMatrix(YawRotation).GetUnitAxis(EAxis::Y);

	FVector MoveDirection = (Forward * MoveInput.X) + (Right * MoveInput.Y);
	MoveDirection = MoveDirection.GetSafeNormal();

	IsMovingForward = (MoveInput.X > 0.0f && FMath::IsNearlyZero(MoveInput.Y));

	LastMoveDirection = MoveDirection;

	SetActorRotation(YawRotation);
	AddMovementInput(MoveDirection, 1.0f);
}

void ATSCharacter2::StartJump(const FInputActionValue& value)
{
	if (value.Get<bool>())
	{
		Jump();
	}
}

void ATSCharacter2::StopJump(const FInputActionValue& value)
{
	if (!value.Get<bool>())
	{
		StopJumping();
	}
}

void ATSCharacter2::Look(const FInputActionValue& value)
{
	FVector2D LookInput = value.Get<FVector2D>();

	// í˜„ì¬ ì»¨íŠ¸ë¡¤ëŸ¬ íšŒì „ê°’
	FRotator ControlRotation = Controller->GetControlRotation();

	// IMCì—ì„œ IA_Lookì— Negateì— Yì¶• ë°˜ì „ì„ êº¼ë„ëì§€ë§Œ
	// ë³´ê¸°í¸í•˜ê²Œ C++ì— ControlRotationì— Pitchê°’ì— ' - 'ë¥¼ ë„£ì–´ì„œ ì¶•ë°˜ì „ì„ ë„£ìŒ
	float NewPitch = ControlRotation.Pitch - LookInput.Y;

	// Pitch ê°ë„ë¥¼ -30 ~ 40ë„ë¡œ ì œí•œ
	NewPitch = FMath::Clamp(NewPitch, MaxLookDownAngle, MaxLookUpAngle);

	// ì œí•œëœ Pitchê°’ì„ ì ìš©í•˜ê³ , Yawê°’ì€ ê·¸ëŒ€ë¡œë‘ì–´ Pitchê°’ì— Maxì¹˜ë§Œ ì ìš©í•¨
	Controller->SetControlRotation(FRotator(NewPitch, ControlRotation.Yaw + LookInput.X, 0.0f));
}

void ATSCharacter2::StartSprint(const FInputActionValue& value)
{
	// ì¬ì¥ì „ ì¤‘ì´ë©´ Sprint ë¶ˆê°€í•˜ê²Œ ë§Œë“¬
	if (!GetCharacterMovement() || bIsReloading) return;

	// ì¡°ì¤€ ì¤‘ì´ë©´ StopAimingìœ¼ë¡œ ì¡°ì¤€ í•´ì œ
	if (bIsAiming)
	{
		StopAiming(value);
	}

	if (LastMoveInput.X > 0.0f && FMath::IsNearlyZero(LastMoveInput.Y))
	{
		GetCharacterMovement()->MaxWalkSpeed = SprintSpeed;
	}
}


void ATSCharacter2::StopSprint(const FInputActionValue& value)
{
	if (GetCharacterMovement())
	{
		GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
	}

	// ì¡°ì¤€ê³¼ ì¥ì „ì¤‘ì´ ì•„ë‹ˆë©´ ê¸°ë³¸ ì†ë„ë¡œ ëŒì•„ê°„ë‹¤.
	if (!bIsReloading && !bIsAiming) 
	{
		GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
	}
}

void ATSCharacter2::StartCrouch(const FInputActionValue& value)
{
	if (GetCharacterMovement()->IsFalling())
	{
		return;
	}

	Crouch();
}

void ATSCharacter2::StopCrouch(const FInputActionValue& value)
{
	UnCrouch();
}

void ATSCharacter2::Reload(const FInputActionValue& value)
{
	if (bIsReloading || GetCharacterMovement()->IsFalling()) // ì—°ì† ì…ë ¥ ë°©ì§€ ë° ì í”„ ì¤‘ ì¬ì¥ì „ ê¸ˆì§€
	{
		return;
	}

	if (CurrentShotGunBullet < MaxShotGunBullet)
	{
		bIsReloading = true; // ì¬ì¥ì „ ì¤‘ ìƒíƒœ ì„¤ì •

		GetCharacterMovement()->DisableMovement(); // ì´ë™ ì™„ì „ ì°¨ë‹¨

		// ì¬ì¥ì „ ì¿¨ë‹¤ìš´ 3ì´ˆ
		GetWorld()->GetTimerManager().SetTimer(
			ShotgunCooldownTimerHandle,
			this,
			&ATSCharacter2::ResetReloadState,
			3.0f,
			false
		);

	}
}

void ATSCharacter2::Fire(const FInputActionValue& value)
{
	if (GetCharacterMovement()->IsFalling() || !bIsAiming) // ì í”„ë‚˜ ì¡°ì¤€ì¤‘ì´ ì•„ë‹ˆë©´ ë°œì‚¬ ê¸ˆì§€
	{
		return;
	}

	if (GetCharacterMovement())
	{
		GetCharacterMovement()->MaxWalkSpeed = 0.0f;
	}

	if (!bFire && CurrentShotGunBullet > 0) // ì—°ì† ë°œì‚¬ ë°©ì§€ ë° ì´ì•Œì´ ìˆì„ ë•Œë§Œ ì‹¤í–‰
	{
		bFire = true; // ë°œì‚¬ ì¤‘ ìƒíƒœ ì„¤ì •

		// íƒ„ì•½ ê°ì†Œ
		CurrentShotGunBullet = FMath::Clamp(CurrentShotGunBullet - 1, 0, MaxShotGunBullet);

		ATSGameState* GameState = Cast<ATSGameState>(UGameplayStatics::GetGameState(GetWorld()));
		if (GameState)
		{
			GameState->SetShotGunBulletCount(CurrentShotGunBullet); //GameStateë¡œ ë°ì´í„° ì „ì†¡
		}
		
		// Testì¶œë ¥ìš©
		// ================================================================================
		// ================================================================================
		UE_LOG(LogTemp, Warning, TEXT("ì´ì•Œ ë°œì‚¬ í˜„ì¬ ë‚¨ì€ ì´ì•Œ : %d"), CurrentShotGunBullet);

		// ë¬´ê¸° ë°œì‚¬ ì²˜ë¦¬
		if (WeaponChildActor)
		{
			AActor* ChildActor = WeaponChildActor->GetChildActor();
			if (ChildActor)
			{
				AGunWeapon* EquippedWeapon = Cast<AGunWeapon>(ChildActor);
				if (EquippedWeapon)
				{
					EquippedWeapon->FireBullet();
				}
			}
		}

		// ì´ ë°œì‚¬ ì‚¬ìš´ë“œ ì‹¤í–‰
		if (FireSound)
		{
			UGameplayStatics::PlaySoundAtLocation(this, FireSound, GetActorLocation());
		}

		// ì´ì˜ëŠ” ì• ë‹ˆë©”ì´ì…˜ 0.3ì´ˆ ì„¤ì • -> 1ì´ˆë¡œí•˜ë©´ ì™¼ì†ì´ ì¬ì¥ì „í•˜ëŠ”ë° ìƒ·ê±´ ì¬ì¥ì „ ë©”ì‰¬ë¥¼ ì›€ì§ì¼ìˆ˜ê°€ì—†ìŒ
		GetWorld()->GetTimerManager().SetTimer(
			ShotgunCooldownTimerHandle,
			this,
			&ATSCharacter2::ResetFireState,
			0.3f,
			false
		);
	}
}

void ATSCharacter2::StartAiming(const FInputActionValue& value)
{
	if (GetCharacterMovement()->IsFalling()) return;
	if (GetCharacterMovement()->MaxWalkSpeed == SprintSpeed) return;

	bIsAiming = true;

	// ì¹´ë©”ë¼ ì‹œì•¼ê° ì ìš©
	CameraComp->SetFieldOfView(AimFOV);

	// ì¹´ë©”ë¼ì˜ ìœ„ì¹˜
	SpringArmComp->SocketOffset = FVector(200.0f, -50.0f, -20.0f);

	// ì¹´ë©”ë¼ ê°ë„ë¥¼ ì•½ê°„ ì•„ë˜ë¡œ ê¸°ìš¸ì—¬ ì¡°ì¤€ ì‹œ ì´ì´ ì¤‘ì•™ìœ¼ë¡œ ì˜¤ë„ë¡ ì¡°ì •
	SpringArmComp->SetRelativeRotation(FRotator(-8.0f, 5.0f, 0.0f));

	// ìºë¦­í„°ì˜ ì¡°ì¤€ ë°©í–¥ì„ ë§ˆìš°ìŠ¤ ì»¤ì„œ ë°©í–¥ìœ¼ë¡œ íšŒì „
	APlayerController* PlayerController = Cast<APlayerController>(GetController());
	if (PlayerController)
	{
		FVector CameraLocation;
		FRotator CameraRotation;
		PlayerController->GetPlayerViewPoint(CameraLocation, CameraRotation);

		// ì¹´ë©”ë¼ì˜ ë°©í–¥ì„ ë”°ë¼ ì •ë ¬í•˜ë„ë¡ ì„¤ì •
		FRotator NewAimRotation = UKismetMathLibrary::FindLookAtRotation(GetActorLocation(), CameraLocation + CameraRotation.Vector() * 1000.0f);
		NewAimRotation.Pitch = 0.0f; // í”¼ì¹˜ëŠ” ê³ ì •í•˜ì—¬ ìœ„ì•„ë˜ ê°ë„ ì˜í–¥ì„ ìµœì†Œí™”
		NewAimRotation.Roll = 0.0f;
		SetActorRotation(NewAimRotation);
	}
}

void ATSCharacter2::StopAiming(const FInputActionValue& value)
{
	bIsAiming = false;
	CameraComp->SetFieldOfView(DefaultFOV);
	SpringArmComp->SocketOffset = DefaultCameraOffset;

	GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
}



void ATSCharacter2::Death()
{
	if (DeathAnimation)
	{
		UAnimInstance* AnimInstance = GetMesh()->GetAnimInstance();
		if (AnimInstance)
		{
			FName SlotName = TEXT("DeathSlot");
			AnimInstance->Montage_Play(DeathAnimation);
			AnimInstance->Montage_JumpToSection(SlotName, DeathAnimation);
		}
	}

	GetCharacterMovement()->DisableMovement();
	GetCharacterMovement()->StopMovementImmediately();
}


// About Health
void ATSCharacter2::TakeDamage()
{

}

void ATSCharacter2::EnableMovementAfterReload()
{
	GetCharacterMovement()->SetMovementMode(MOVE_Walking);
}

void ATSCharacter2::FaceMouseDirection()
{
	if (!Controller) return;

	FRotator NewRotation = Controller->GetControlRotation();
	NewRotation.Pitch = 0.0f;
	NewRotation.Roll = 0.0f;

	SetActorRotation(NewRotation);
}

void ATSCharacter2::ResetMovementAfterFire()
{
	if (GetCharacterMovement())
	{
		GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;
	}

	IsFiring = false;
}
void ATSCharacter2::ResetFireState()
{
	bFire = false; // Fire ìƒíƒœ í•´ì œ
}

void ATSCharacter2::ResetReloadState()
{
	bIsReloading = false; // ì¬ì¥ì „ ìƒíƒœ í•´ì œ

	GetCharacterMovement()->SetMovementMode(MOVE_Walking); // ì´ë™ ê°€ëŠ¥í•˜ê²Œ ë³µêµ¬
	GetCharacterMovement()->MaxWalkSpeed = NormalSpeed;


	// íƒ„ì•½ ì¦ê°€ ë¡œì§
	if (CurrentShotGunBullet == 0)
	{
		CurrentShotGunBullet = 2; // 0ì´ë©´ 2ë¡œ ì¦ê°€
	}
	else if (CurrentShotGunBullet == 1)
	{
		CurrentShotGunBullet = 2; // 1ì´ë©´ 2ë¡œ ì¦ê°€
	}

	ATSGameState* GameState = Cast<ATSGameState>(UGameplayStatics::GetGameState(GetWorld()));
	if (GameState)
	{
		GameState->SetShotGunBulletCount(CurrentShotGunBullet); //GameStateë¡œ ë°ì´í„° ì „ì†¡
	}
	
	// Testì¶œë ¥ìš©
	// ================================================================================
	// ================================================================================
	UE_LOG(LogTemp, Warning, TEXT("ìƒ·ê±´ ì¥ì „ í˜„ì¬ ì´ì•Œ : %d"), CurrentShotGunBullet);

}

int32 ATSCharacter2::GetCurrentShotGunBullet() const
{
	return CurrentShotGunBullet;
}


void ATSCharacter2::PlayFootstepSound()
{
	if (GetCharacterMovement()->IsFalling())
	{
		return;
	}

	if (!GetCharacterMovement() || !bCanPlayFootstep) return;

	float CurrentSpeed = GetCharacterMovement()->Velocity.Size();

	// ì†ë„ê°€ 10 ì´í•˜ì´ë©´ ì •ì§€ ìƒíƒœë¡œ íŒë‹¨í•˜ê³  ì¬ìƒ X
	if (CurrentSpeed <= 10.0f)
	{
		return;
	}

	USoundCue* FootstepSound = nullptr;

	// ì†ë„ì— ë”°ë¼ ê±·ëŠ” ì†Œë¦¬ ë˜ëŠ” ë›°ëŠ” ì†Œë¦¬ ì„ íƒ
	if (CurrentSpeed > 300.0f)
	{
		FootstepSound = SprintSound; // ë›°ëŠ” ì‚¬ìš´ë“œ
	}
	else
	{
		FootstepSound = WalkSound; // ê±·ëŠ” ì‚¬ìš´ë“œ
	}

	// ì‚¬ìš´ë“œê°€ ì¡´ì¬í•˜ë©´ ì‹¤í–‰
	if (FootstepSound)
	{
		UGameplayStatics::PlaySoundAtLocation(this, FootstepSound, GetActorLocation());

		// ğŸ”¹ ë‹¤ìŒ ë°œì†Œë¦¬ê°€ ì¼ì • ì‹œê°„ í›„ì—ë§Œ ì¬ìƒë˜ë„ë¡ íƒ€ì´ë¨¸ ì„¤ì •
		bCanPlayFootstep = false;
		float FootstepDelay = (CurrentSpeed > 300.0f) ? 0.23f : 0.5f; // ë›°ëŠ” ê²½ìš° 0.3ì´ˆ, ê±·ëŠ” ê²½ìš° 0.5ì´ˆ
		GetWorld()->GetTimerManager().SetTimer(
			FootstepTimerHandle,
			this,
			&ATSCharacter2::ResetFootStep,
			FootstepDelay,
			false);
	}
}

void ATSCharacter2::ResetFootStep()
{
	bCanPlayFootstep = true;
}